micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1
